var MigratoryDataClient={};
MigratoryDataClient.a=function(){return navigator.userAgent&&navigator.userAgent.indexOf("ANTGalio")!==-1?"Opera":navigator.userAgent&&navigator.userAgent.indexOf("Chrome")!==-1&&navigator.userAgent.indexOf("WebKit")!==-1?"WebKit Chrome":navigator.userAgent&&navigator.userAgent.indexOf("Android")!==-1?"WebKit Android":navigator.userAgent&&navigator.userAgent.indexOf("iPhone")!==-1?"WebKit iPhone":navigator.userAgent&&navigator.userAgent.indexOf("WebKit")!==-1?"WebKit":navigator.userAgent&&navigator.userAgent.indexOf("MSIE")!==
-1?"IE":navigator.userAgent&&navigator.userAgent.indexOf("Gecko")!==-1?"Gecko":navigator.userAgent&&navigator.userAgent.indexOf("Opera Mobi")!==-1?"Opera Mobile":navigator.userAgent&&navigator.userAgent.indexOf("Opera Mini")!==-1?"unknown":window.opera?"Opera":"unknown"};MigratoryDataClient.b=function(a){if(!document.body)throw"Error: The document doesn't have a body!";var b=true;if(this.c==="unknown"){b=false;if(a)if(this.d===null)throw"Error: Browser not supported!";else this.d(this.NOTIFY_UNSUPPORTED_BROWSER)}return b};
MigratoryDataClient.e=function(){if(document.readyState==="complete"||document.readyState==="interactive")this.f();else if(document.addEventListener){document.addEventListener("DOMContentLoaded",this.f,false);window.addEventListener("load",this.f,false)}else if(document.attachEvent){document.attachEvent("onreadystatechange",this.f);window.attachEvent("onload",this.f);var a=false;try{a=window.frameElement==null}catch(b){}document.documentElement.doScroll&&a&&this.g()}};
MigratoryDataClient.g=function(){if(!MigratoryDataClient.h){try{document.documentElement.doScroll("left")}catch(a){setTimeout(MigratoryDataClient.g,1);return}MigratoryDataClient.f()}};MigratoryDataClient.i=function(a){this.h?a():this.j.push(a)};MigratoryDataClient.f=function(){if(!MigratoryDataClient.h)if(document.body){MigratoryDataClient.h=true;for(var a=0;a<MigratoryDataClient.j.length;a++)MigratoryDataClient.j[a]();MigratoryDataClient.j=null}else setTimeout(MigratoryDataClient.f,13)};
MigratoryDataClient.k=function(a){var b=window.location.protocol,c=window.location.host,d=window.location.port;if(c.indexOf("localhost")===0)return{l:"localhost:80",m:a+"/"};if(d.length>0&&c.lastIndexOf(":")!==-1)c=c.substring(0,c.lastIndexOf(":"));var e=a.indexOf("//");if(e===-1)return null;var g=a.substring(0,e);if(b!==g)return null;a=a.substring(g.length+2);e=a.indexOf("/");if(e!==-1)a=a.substring(0,e);e=a.lastIndexOf(":");b="";if(e!==-1){b=a.substring(e+1);a=a.substring(0,e)}if(navigator.userAgent&&
navigator.userAgent.indexOf("ANTGalio")!==-1){e=80;if(g==="https:")e=443;if(b!==""&&b!==e&&d!==e)if(b!==d)return null}else if(b!==d)return null;if(a.length<4)return null;var f=-1;e=a.length-1;for(var i=c.length-1;e>=0&&i>=0;e--,i--)if(a.charAt(e)!==c.charAt(i)){f=e;break}d="";if(f===-1)if(e===-1&&i===-1){e=a.indexOf(".");d=a.substring(e+1)}else if(e===-1)if(c.charAt(i-1)===".")d=a;else{e=a.indexOf(".");if(e===-1)return null;d=a.substring(e+1)}else{if(i===-1)if(a.charAt(e-1)===".")d=c;else{e=c.indexOf(".");
if(e===-1)return null;d=c.substring(e+1)}}else{e=a.indexOf(".",f+1);if(e===-1)return null;d=a.substring(e+1)}if(d.length<4||d.indexOf(".")===-1)return null;d+=b.length>0?":"+b:"";a=g+"//"+a+(b.length>0?":"+b:"")+"/";if(this.n>=2){c=d.split(".");if(c.length>=this.n)d=c.slice(-1*this.n).join(".")}return{l:d,m:a}};MigratoryDataClient.o=function(a){return this.k(a)===null};
MigratoryDataClient.p=function(a,b){if(a.name)a=a.name;else{var c=a.toString();a=c.substring(c.indexOf("function")+8,c.indexOf("("));a=a.replace(/^\s+|\s+$/g,"");if(a.length===0)a="anonymous";if(a==="anonymous"&&typeof b==="object")for(var d=0;d<b.length;d++)for(var e in b[d])if(b[d].hasOwnProperty(e)&&typeof b[d][e]==="function")if(b[d][e].toString()===c)return e}return a};
MigratoryDataClient.q=function(a){if(a===null||a===undefined||typeof a==="number"||typeof a==="boolean")return a;else if(typeof a==="string")return'"'+a+'"';else if(typeof a==="function")return this.p(a,this)+"()";else if(a instanceof Array)return this.r(a);var b="{",c=0;for(var d in a){if(c>0)b+=", ";if(a.hasOwnProperty(d))b+=d+":"+this.q(a[d]);c++}b+="}";return b};
MigratoryDataClient.s=function(){return"xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx".replace(/[xy]/g,function(a){var b=Math.random()*16|0;return(a=="x"?b:b&3|8).toString(16)})};
MigratoryDataClient.t=function(a,b){var c=MigratoryDataClient.u;if(a>0){if(a<=this.v)c=a*MigratoryDataClient.w-Math.floor(Math.random()*MigratoryDataClient.w);else if(MigratoryDataClient.x===MigratoryDataClient.TRUNCATED_EXPONENTIAL_BACKOFF){a=a-this.v;c=Math.min(MigratoryDataClient.y*Math.pow(2,a)-Math.floor(Math.random()*MigratoryDataClient.y*a),MigratoryDataClient.z)}else c=MigratoryDataClient.y;if(b!==undefined&&c<MigratoryDataClient.u)c=MigratoryDataClient.u}return c};
MigratoryDataClient.a0=function(a,b){var c={};if(b.length>0)for(var d=0;d<b.length;d++)c[b[d]]=a[b[d]];else for(d in a)c[d]=a[d];return c};MigratoryDataClient.a1=function(a,b){for(var c=0;c<a.length;c++)if(a[c]===b)return c;return-1};MigratoryDataClient.a2=function(a){for(var b=[],c=0;c<a.length;c++)b.push(a[c]);return b};MigratoryDataClient.a3=function(a,b){for(var c=[],d=0;d<a.length;d++)this.a1(b,a[d])===-1&&c.push(a[d]);return c};
MigratoryDataClient.a4=function(a,b){for(var c=[],d=0;d<a.length;d++)this.a1(b,a[d])!==-1&&c.push(a[d]);return c};MigratoryDataClient.a5=function(a,b){for(var c=this.a2(a),d=0;d<b.length;d++)this.a1(a,b[d])===-1&&c.push(b[d]);return c};
MigratoryDataClient.a6=function(a,b,c,d,e,g){if(typeof b!=="object"||typeof b.length!=="number")throw"Error: "+a+" - invalid argument; expected a list";if(d!==null&&b.length<d)throw"Error: "+a+" - invalid argument; expected a list with a least "+d+" elements";if(c!==null)for(d=0;d<b.length;d++)if(typeof b[d]!==c)throw"Error: "+a+" - invalid argument; the element on the position '"+d+"' is not of type '"+c+"'";if(typeof e==="object"&&typeof e.test==="function")for(d=0;d<b.length;d++)if(!e.test(b[d]))throw"Error: "+
a+". "+g+"; the element on the position '"+d+"' is the cause of the error";};MigratoryDataClient.r=function(a){for(var b="[",c=0;c<a.length;c++){if(c>0)b+=", ";b+=this.q(a[c])}b+="]";return b};MigratoryDataClient.a7=function(a,b,c,d,e){this.a6(a,b,c,d,/^\/[^\/*]+\/([^\/*]+\/)*([^\/*]+|\*)$/,e)};
MigratoryDataClient.a8=function(a,b){if(a===this.a9.aa)this.ab(b);else if(a===this.a9.ac)this.ad(b);else if(a===this.a9.ae)this.af(b);else if(a===this.a9.ag)this.ah(b);else if(a!==this.a9.ai)if(this.aj!==null)if(this.aj.ak===this.al&&a===this.a9.al)this.am(b);else if(this.aj.ak===this.an&&a===this.a9.an)this.ao(b);else this.aj.ak===this.ap&&a===this.a9.ap&&this.aq(b)};
MigratoryDataClient.am=function(a){var b=a[this.a9.as];if(b!==undefined)this.at(this.au,this.av.aw[b]);else{if(this.ax!==this.ay){b=a[this.a9.az];if(b===undefined){MigratoryDataClient.at(this.au,"server subscribe response is missing the session id");return}this.b0=b;b=a[this.a9.b1];if(b!==undefined&&b!==null)if(b==1)MigratoryDataClient.b2=true;b=a[this.a9.b3];if(b!==undefined&&b!==null)MigratoryDataClient.b4=b*1E3*1.4;this.b5=a[this.a9.b6];b=this.ax;this.ax=this.ay;this.b8=this.b7=0;this.b9();this.bb(a[this.a9.ba]);
if(b!==this.bc){this.bd.be[this.bf]!==undefined&&this.bd.be[this.bf].bg++;if(b===null||this.bh)this.bj({type:this.NOTIFY_SERVER_UP,info:this.bi[this.bf].m})}else this.bd.be[this.bf]!==undefined&&this.bd.be[this.bf].bk++;this.bh=false}this.bl()}};MigratoryDataClient.ao=function(a){a=a[this.a9.as];a!==undefined?this.at(this.au,this.av.aw[a]):this.bl()};MigratoryDataClient.aq=function(a){a=a[this.a9.as];a!==undefined?this.at(this.au,this.av.aw[a]):this.bl()};
MigratoryDataClient.ab=function(a){var b=this.a9.bm,c=this.a9.bn,d=this.a9.bo,e=this.a9.bp,g=this.a9.bq;if(!(a[b]===undefined||a[c]===undefined))if(this.br[a[b]]!==undefined){this.bb(a[this.a9.ba]);var f=false;if(a[g]!==undefined&&a[g]==1)f=true;g=this.MESSAGE_TYPE_UPDATE;if(a[d]!==undefined)g=a[d]==this.bs?this.MESSAGE_TYPE_SNAPSHOT:a[d]==this.bt?this.MESSAGE_TYPE_RECOVERED:a[d]==this.bu?this.MESSAGE_TYPE_HISTORICAL:this.MESSAGE_TYPE_UPDATE;b={subject:a[b],content:a[c],replySubject:a[e],retained:f,
type:g,qos:MigratoryDataClient.QOS_STANDARD,seq:0,epoch:0};c=this.a9.bv;if(a[c]!==undefined){c=((new Date).getTime()&16777215)-a[c];if(c>-14400000)b.latency=c}if(MigratoryDataClient.b2==true&&this.bw(a)==true){c=parseInt(a[this.a9.bx]);a=parseInt(a[this.a9.by]);b.qos=MigratoryDataClient.QOS_GUARANTEED;b.seq=a;b.epoch=c;a=this.bz(b.subject,this.br[b.subject],a,c);if(a!="in_order")if(a=="higher"){MigratoryDataClient.c0();return}}this.bd.be[this.bf]!==undefined&&this.bd.be[this.bf].c1++;this.bj({message:b})}};
MigratoryDataClient.bw=function(a){var b=this.a9.c2,c=true;if(a[b]!==undefined&&parseInt(a[b])==MigratoryDataClient.c3)c=false;return c};
MigratoryDataClient.bz=function(a,b,c,d){if(b.seqid!=d){b.seq=c;b.messagesReceivedUntilRecovery++;b.seqid=d;return"in_order"}if(c<=b.seq)return"lower";if(c==b.seq+1){if(b.currentSubscribeType==MigratoryDataClient.c4){b.currentSubscribeType=MigratoryDataClient.c5;a={type:this.NOTIFY_DATA_SYNC,info:a};this.bj(a)}b.seq+=1;b.messagesReceivedUntilRecovery++;return"in_order"}if(b.messagesReceivedUntilRecovery>0)return"higher";b.seq=c;b.messagesReceivedUntilRecovery++;a={type:this.NOTIFY_DATA_RESYNC,info:a};
this.bj(a);return"in_order"};MigratoryDataClient.at=function(a,b){a=a+", "+b;b=this.bd.be[this.bf].aw;if(b[a]===undefined)b[a]=1;else b[a]++;this.b8++;this.c0()};
MigratoryDataClient.ad=function(a){var b=this.a9.c6,c=this.a9.bm;if(!(a[b]===undefined||a[c]===undefined)){var d=true,e=this.NOTIFY_SUBSCRIBE_DENY;switch(a[b]){case "a":e=this.NOTIFY_SUBSCRIBE_ALLOW;d=false;break;case "d":b=a[this.a9.as];if(b!==undefined){if(b==MigratoryDataClient.c7)e=this.NOTIFY_SUBSCRIBE_TIMEOUT}else e=this.NOTIFY_SUBSCRIBE_DENY;break}if(d===true){this.c8=this.a3(this.c8,[a[c]]);delete this.br[a[c]]}this.bj({type:e,info:a[c]})}};
MigratoryDataClient.bj=function(a){this.c9.push(a);setTimeout(function(){var b=MigratoryDataClient.c9.shift();if("message"in b)MigratoryDataClient.ca.call(window,b.message);else MigratoryDataClient.d!==null&&MigratoryDataClient.d.call(window,b)},0)};MigratoryDataClient.af=function(a){a!==undefined&&a!==null&&Object.keys(a).length>0&&this.cb(a)};MigratoryDataClient.cb=function(a){var b=a[this.a9.cc];a=a[this.a9.c6];b!==undefined&&b!==null&&this.bj({type:MigratoryDataClient.cd(a),info:b})};
MigratoryDataClient.ah=function(a){var b=a[this.a9.bm];a=a[this.a9.bo];if(MigratoryDataClient.ce==a)for(a=0;a<this.c8.length;a++){b=this.br[this.c8[a]];var c=b.cacheRecoveryStatus;if(MigratoryDataClient.cf==c||MigratoryDataClient.cg==c||MigratoryDataClient.ch==c)b.nrOfConsecutiveRecovery=0;else{b.messagesReceivedUntilRecovery=0;b.seqid!=Number.MAX_SAFE_INTEGER&&b.nrOfConsecutiveRecovery++}}else{b=this.br[b];if(b!==null)b.cacheRecoveryStatus=a}};
MigratoryDataClient.cd=function(a){if(a===undefined||a===null)return MigratoryDataClient.NOTIFY_PUBLISH_FAILED;switch(a){case "OK":return MigratoryDataClient.NOTIFY_PUBLISH_OK;case "DENY":return MigratoryDataClient.NOTIFY_PUBLISH_DENIED;default:return MigratoryDataClient.NOTIFY_PUBLISH_FAILED}};
MigratoryDataClient.bb=function(a){if(a!==undefined)if(this.ci==null)this.ci=a;else if(a!==this.ci){this.ci=a;for(a=0;a<this.c8.length;a++)this.br[this.c8[a]]={seqid:Number.MAX_SAFE_INTEGER,seq:0,history:this.br[this.c8[a]].history,nrOfConsecutiveRecovery:0,messagesReceivedUntilRecovery:0,cacheRecoveryStatus:MigratoryDataClient.cf,currentSubscribeType:MigratoryDataClient.c5}}};
MigratoryDataClient.cj=function(){this.bd.ck=(new Date).getTime();this.bd.be[this.bf]!==undefined&&this.bd.be[this.bf].cl++;this.cm!==null&&this.b9();this.aj!==null&&this.aj.ak===this.ai&&this.bl();var a=(new Date).getTime();if(a-this.cn>=this.co){this.cn=a;a={};a.ak=this.ai;this.cp(a)}};MigratoryDataClient.b9=function(){this.cm!==null&&clearTimeout(this.cm);if(this.b4>0)this.cm=setTimeout(function(){MigratoryDataClient.b8++;MigratoryDataClient.c0()},this.b4)};
MigratoryDataClient.c0=function(){this.bd.be[this.bf]!==undefined&&this.bd.be[this.bf].cq++;if((new Date).getTime()-this.cr<18E4)this.cs++;else{this.cs=0;this.cr=(new Date).getTime()}if(this.cs>=MigratoryDataClient.ct){var a={type:this.NOTIFY_RECONNECT_RATE_EXCEEDED,info:""};MigratoryDataClient.d!==null&&MigratoryDataClient.d.call(window,a);MigratoryDataClient.getSubjects();a=[];for(var b=0;b<MigratoryDataClient.bi.length;b++)a[b]=MigratoryDataClient.bi[b].cu+" "+MigratoryDataClient.bi[b].m;MigratoryDataClient.disconnect();
MigratoryDataClient.connect()}else{if(this.cv!==null){clearTimeout(this.cv);this.cv=null}this.cw();this.cx();this.cy();if(this.ax!==null)this.ax=this.cz;a=this.bi[this.bf].m;this.d0.push(this.bi[this.bf]);this.b5=this.b0=this.bf=null;this.b7++;if(this.cm!==null){clearTimeout(this.cm);this.cm=null}if(!this.bh&&(this.b7===this.d1||this.b7===this.bi.length)){this.bh=true;a={type:this.NOTIFY_SERVER_DOWN,info:a};MigratoryDataClient.d!==null&&MigratoryDataClient.d.call(window,a)}if(this.bi.length>0){a=
{};a.ak=this.al;this.cp(a)}if(this.c8.length>0){a={};a.ak=this.an;a.c8=this.c8;this.cp(a)}}};
MigratoryDataClient.d2=function(){this.bd.be[this.bf]!==undefined&&this.bd.be[this.bf].cq++;if((new Date).getTime()-this.cr<18E4)this.cs++;else{this.cs=0;this.cr=(new Date).getTime()}if(this.cv!==null){clearTimeout(this.cv);this.cv=null}MigratoryDataClient.d3=null;this.cw();this.cx();this.cy();if(this.ax!==null)this.ax=this.cz;var a=this.bi[this.bf].m;this.d0.push(this.bi[this.bf]);this.b5=this.b0=this.bf=null;this.b7++;if(this.cm!==null){clearTimeout(this.cm);this.cm=null}if(!this.bh&&(this.b7===
this.d1||this.b7===this.bi.length)){this.bh=true;a={type:this.NOTIFY_SERVER_DOWN,info:a};MigratoryDataClient.d!==null&&MigratoryDataClient.d.call(window,a)}};MigratoryDataClient.d4=function(){this.bl();if(this.bi.length>0){var a={};a.ak=this.al;this.cp(a)}if(this.c8.length>0){a={};a.ak=this.an;a.c8=this.c8;this.cp(a)}};
MigratoryDataClient.d5=function(){this.d6();var a=false,b=this.bi[this.bf].m,c=this.o(b);if(!MigratoryDataClient.d7){if(!this.d8||!c)b=this.d9(b);if(!c&&!this.da(b,this.bf))return}var d=c&&!this.db?this.dc:null,e=null,g=null,f=this.dd,i=this.a9,j=null,h=null;if(MigratoryDataClient.d7){f=this.de;d=this.df}else if(this.c==="IE"&&c&&MigratoryDataClient.dg){f=this.dh;i=this.di;d=this.dj}if(this.ax!==this.ay){if(!MigratoryDataClient.d7)if(this.c==="IE"&&!c)if(this.dk){d=this.dl;f=this.dm}else{d=this.dn;
e="MigratoryDataClient0.dp";g=this.dq;f=this.dr;i=this.di}else if(this.c==="IE"&&MigratoryDataClient.dg&&this.dk){a=true;d=this.dl;f=this.ds;i=this.di}else{f=this.dt;if(this.c==="WebKit Android")f=this.du;d=c&&!this.db?this.dc:f;f=this.dv}j=navigator.userAgent;h=this.dw}c="";c+=this.dx(d,e,g,i,this.dy,a,j,h,this.dz);if("/"!==b.substring(b.length-1,b.length))b+="/";a=MigratoryDataClient.t(this.b8,this.al);this.e0=setTimeout(function(){MigratoryDataClient.e0=null;MigratoryDataClient.at(MigratoryDataClient.e1,
MigratoryDataClient.aj.ak)},a);f.call(this,b,this.bf,c)};
MigratoryDataClient.e2=function(){this.d6();var a=this.bi[this.bf].m,b=this.o(a);if(!MigratoryDataClient.d7){if(!this.d8||!b)a=this.d9(a);if(!b&&!this.da(a,this.bf))return}this.c8=this.a5(this.c8,this.aj.c8);var c=b&&!this.db?this.dc:null,d=this.dd,e=this.a9;if(MigratoryDataClient.d7){d=this.e3;c=this.df}else if(this.c==="IE"&&b&&MigratoryDataClient.dg){d=this.dh;e=this.di;c=this.dj}b="";for(var g=0;g<this.aj.c8.length;g++){var f=this.aj.c8[g];if(this.aj.e4!==undefined&&this.aj.e4===true)this.br[f]=
{seqid:Number.MAX_SAFE_INTEGER,seq:0,history:this.aj.e5[f],nrOfConsecutiveRecovery:0,messagesReceivedUntilRecovery:0,cacheRecoveryStatus:MigratoryDataClient.cf,currentSubscribeType:MigratoryDataClient.c5};b+=this.e6(f,this.br[f],c,this.b0,e)}if("/"!==a.substring(a.length-1,a.length))a+="/";c=MigratoryDataClient.u;if(MigratoryDataClient.d7===false)c=MigratoryDataClient.t(this.b8,this.an);this.e0=setTimeout(function(){MigratoryDataClient.e0=null;MigratoryDataClient.at(MigratoryDataClient.e1,MigratoryDataClient.aj.ak)},
c);d.call(this,a,this.bf,b)};
MigratoryDataClient.e7=function(){this.d6();var a=this.bi[this.bf].m,b=this.o(a);if(!MigratoryDataClient.d7){if(!this.d8||!b)a=this.d9(a);if(!b&&!this.da(a,this.bf))return}this.c8=this.a3(this.c8,this.aj.c8);if(this.ax!==this.ay){this.bl();for(b=0;b<this.aj.c8.length;b++)delete this.br[this.aj.c8[b]]}else{var c=b&&!this.db?this.dc:null,d=this.dd,e=this.a9;if(MigratoryDataClient.d7){c=this.df;d=this.e3}else if(this.c==="IE"&&b&&MigratoryDataClient.dg&&this.dk){d=this.dh;e=this.di;c=this.dj;if("/"!==
a.substring(a.length-1,a.length))a+="/"}var g="";for(b=0;b<this.aj.c8.length;b++){var f=this.aj.c8[b];g+=this.e8(f,this.br[f],c,this.b0,e);delete this.br[f]}this.e0=setTimeout(function(){MigratoryDataClient.e0=null;MigratoryDataClient.at(MigratoryDataClient.e1,MigratoryDataClient.aj.ak)},this.u);d.call(this,a,this.bf,g)}};
MigratoryDataClient.e9=function(){this.d6();var a=this.bi[this.bf].m,b=this.o(a);if(!MigratoryDataClient.d7){if(!this.d8||!b)a=this.d9(a);if(!b&&!this.da(a,this.bf))return}if(this.ax!==this.ay)this.bl();else{var c=b&&!this.db?this.dc:null,d=this.dd,e=this.a9,g=this.b5;if(MigratoryDataClient.d7){c=this.df;d=this.e3;g=null}else if(this.c==="IE"&&b&&MigratoryDataClient.dg&&this.dk){d=this.dh;e=this.di;c=this.dj;if("/"!==a.substring(a.length-1,a.length))a+="/"}b=MigratoryDataClient.ea(this.b0,e,c,g);
this.e0=setTimeout(function(){MigratoryDataClient.e0=null;MigratoryDataClient.at(MigratoryDataClient.e1,MigratoryDataClient.aj.ak)},this.u);d.call(this,a,this.bf,b)}};
MigratoryDataClient.eb=function(){this.d6();var a=this.bi[this.bf].m,b=this.o(a);if(!MigratoryDataClient.d7){if(!this.d8||!b)a=this.d9(a);if(!b&&!this.da(a,this.bf))return}var c=b&&!this.db?this.dc:null,d=this.dd,e=this.a9;if(this.ax!==this.ay){a=this.aj.ec.closure;a!==undefined&&a!==null&&this.bj({type:MigratoryDataClient.NOTIFY_PUBLISH_FAILED,info:a})}else{var g=this.dy,f=this.b5;if(MigratoryDataClient.d7){d=this.e3;c=this.df;f=g=null}else if(this.c==="IE"&&b&&MigratoryDataClient.dg){d=this.dh;
e=this.di;c=this.dj}b=this.ed(this.aj.ec,c,this.b0,e,g,f);if("/"!==a.substring(a.length-1,a.length))a+="/";d.call(this,a,this.bf,b)}};MigratoryDataClient.bl=function(a){if(this.ee.length!==0)if(a!==undefined&&a!==null){if(this.ee[0].ak===a){this.ee.shift();this.cx();this.ef(false)}}else{this.ee.shift();this.cx();this.ef(false)}};MigratoryDataClient.cp=function(a){this.ee.push(a);this.eg(false)};
MigratoryDataClient.ef=function(a){this.ee.length!==0&&setTimeout(function(){MigratoryDataClient.eg(a)},0)};MigratoryDataClient.eg=function(a){if(this.eh)if(this.b(true))if(!(!a&&(this.aj!==null||this.ee.length===0))){this.aj=this.ee[0];switch(this.aj.ak){case this.an:this.e2();break;case this.ap:this.e7();break;case this.ai:this.e9();break;case this.al:this.d5();break;case this.ar:this.eb();this.bl();break;case this.ei:this.d2();break;case this.ej:this.d4();break}}};
MigratoryDataClient.ek=function(){this.eh=true;this.ef(false)};
MigratoryDataClient.cw=function(){for(;this.ee.length>0;){var a=this.ee[0];switch(a.ak){case this.an:var b=this.a3(a.c8,this.c8);if(b.length>0){this.c8=this.a5(this.c8,b);if(a.e4!==undefined&&a.e4===true)for(var c=0;c<b.length;c++)this.br[b[c]]={seqid:Number.MAX_SAFE_INTEGER,seq:0,history:a.e5[b[c]],nrOfConsecutiveRecovery:0,messagesReceivedUntilRecovery:0,cacheRecoveryStatus:MigratoryDataClient.cf,currentSubscribeType:MigratoryDataClient.c5}}break;case this.ap:b=this.a4(a.c8,this.c8);if(b.length>
0){this.c8=this.a3(this.c8,b);for(c=0;c<b.length;c++)delete this.br[b[c]]}break;case this.ar:if(a.ec.closure!==undefined&&a.ec.closure!==null){a={type:this.NOTIFY_PUBLISH_FAILED,info:a.ec.closure};MigratoryDataClient.d!==null&&MigratoryDataClient.d.call(window,a)}break}this.ee.shift()}};
MigratoryDataClient.cx=function(){this.aj=null;if(this.e0!==null){clearTimeout(this.e0);this.e0=null}if(this.el!==null&&this.el.readyState&&this.el.readyState!==4){if(typeof XMLHttpRequest!=="undefined")this.el.aborted=true;this.el.abort()}this.el!==null&&delete this.el;this.el=null};
MigratoryDataClient.cy=function(){if(this.em!==null){var a="";if(this.em.en!==undefined)a=this.em.en;if(a!=="HTML5")if(a==="XDR_HTML5"){a=document.getElementById("MigratoryDataClient1");a!==null&&a.contentWindow.postMessage("disconnect","*")}else if(this.em.getElementById){a=this.em.getElementById("eo");if(a!==null){a.src="";this.em.body.removeChild(a);delete a;a=null}delete this.em;this.em=null;CollectGarbage()}else{if(MigratoryDataClient.d7){this.em.onmessage=function(){};this.em.onopen=function(){};
this.em.onclose=function(){};this.em.close()}else{if(this.em.ep!==undefined){clearTimeout(this.em.ep);this.em.ep=undefined}this.em.readyState&&this.em.readyState!==4&&this.em.abort();a==="XDR_STREAM"&&this.em.abort()}delete this.em;this.em=null}}};
MigratoryDataClient.eq=function(){this.cx();this.cy();this.ax=this.bf=null;this.c8=[];this.b5=this.b0=null;this.d0=[];this.cs=this.b7=0;this.cr=(new Date).getTime();this.b8=0;this.bh=false;this.ee=[];this.br={};this.b2=false;if(this.cm!==null){clearTimeout(this.cm);this.cm=null}};
MigratoryDataClient.et=function(){if(this.o(this.bi[this.bf].m)&&!this.db){if(this.em!==null){this.em.responseText="";this.em.eu=0}}else{this.ax=this.bc;this.cy();this.b5=this.b0=null;if(this.bi.length>0){var a={};a.ak=this.al;this.cp(a)}if(this.c8.length>0){a={};a.ak=this.an;a.c8=this.c8;this.cp(a)}}};MigratoryDataClient.d6=function(){if(this.bf===null)this.bf=this.ev()};
MigratoryDataClient.ev=function(){var a=this.a3(this.bi,this.d0);if(a.length===0){this.d0=[];a=this.bi}if(a.length===0)throw"Error: ev() No available servers!";for(var b=0,c=0;c<a.length;c++)b+=a[c].cu;var d=-1;if(b===0)d=Math.floor(a.length*Math.random());else{var e=Math.floor(b*Math.random());for(c=b=0;c<a.length;c++){b+=a[c].cu;if(b>e){d=c;break}}}return this.a1(this.bi,a[d])};
MigratoryDataClient.d9=function(a){var b=this.k(a);if(b===null||this.dq!==null&&b.l!==this.dq)throw"Error: Invalid common parent domain of the servers! Cause server is '"+a+"'.";if(this.dq===null){this.dq=b.l;if(b.l.indexOf(":")===-1)document.domain=b.l}return b.m};MigratoryDataClient.da=function(a,b){var c="MigratoryDataClient2"+b;if(window.frames[c]===undefined||window.frames[c].ew===undefined){this.ex(a,b);return false}return true};
MigratoryDataClient.ex=function(a,b){b="MigratoryDataClient2"+b;var c=document.getElementById(b);if(!c){c=document.createElement("iframe");c.name=b;c.id=b;c.style.display="none";document.body.appendChild(c)}b=MigratoryDataClient.t(this.b8,this.an);this.e0=setTimeout(function(){MigratoryDataClient.e0=null;c.src="";c.parentNode.removeChild(c);MigratoryDataClient.at(MigratoryDataClient.e1,"iframe")},b);if("/"!==a.substring(a.length-1,a.length))a+="/";c.src=a+"_"+this.ey(this.dq,"ew","MigratoryDataClient.ez")};
MigratoryDataClient.ez=function(){clearTimeout(this.e0);this.e0=null;this.ef(true)};MigratoryDataClient.f0=function(a){return this.db?new XMLHttpRequest:this.f1(a)};
MigratoryDataClient.f1=function(a){if(a){if(this.f2)this.f2.responseText="";else this.f2={open:function(b,c){b=MigratoryDataClient.f3(c);MigratoryDataClient.f4.connect("0",b.host,b.port,"MigratoryDataClient.f5")},setRequestHeader:function(){},send:function(b){MigratoryDataClient.f4.write("0","POST / HTTP/1.1\r\nContent-Length: "+b.length+"\r\n\r\n"+b)},readyState:4,status:200,responseText:"",abort:function(){this.responseText="";MigratoryDataClient.f4.close("0")}};return this.f2}if(this.f6)this.f6.responseText=
"";else this.f6={open:function(b,c){b=MigratoryDataClient.f3(c);MigratoryDataClient.f4.connect("1",b.host,80,"MigratoryDataClient.f7")},setRequestHeader:function(){},send:function(b){MigratoryDataClient.f4.write("1","POST / HTTP/1.1\r\nContent-Length: "+b.length+"\r\n\r\n"+b)},readyState:4,status:200,responseText:"",abort:function(){this.responseText="";MigratoryDataClient.f4.close("1")}};return this.f6};
MigratoryDataClient.f3=function(a){var b,c;b=a.indexOf("https://")==0?"https://":"http://";a=a.substring(b.length);var d=a.indexOf("/");if(d!=-1){c=a.substring(0,d);a.substring(d)}else c=a;d=c.lastIndexOf(":");if(d!=-1){a=c.substring(d+1);c=c.substring(0,d)}else a=b=="https://"?"443":"80";return{host:c,port:a}};MigratoryDataClient.f7=function(a){if(this.el){this.el.responseText+=a;this.f8()}};MigratoryDataClient.f5=function(a){if(this.em){this.em.responseText+=a;this.f9()}};
MigratoryDataClient.fa=function(){this.b(false);var a=document.createElement("div");document.body.appendChild(a);var b=document.createElement("div");b.id="MigratoryDataClient3";a.appendChild(b);setTimeout(function(){var c="flash-transport.swf";if(typeof MigratoryDataClientFlashTransport==="string")c=MigratoryDataClientFlashTransport;swfobject.embedSWF(c,"MigratoryDataClient3","0","0","9",false,{readyCallback:"MigratoryDataClient.fb"},{allowFullScreen:false,allowScriptAccess:"always"},{id:"MigratoryDataClient4",
name:"MigratoryDataClient4"})},0)};MigratoryDataClient.fb=function(){MigratoryDataClient.f4=document.getElementById("MigratoryDataClient4");if(!MigratoryDataClient.f4)throw"Error: Could not get the reference of the flash-transport.swf!";MigratoryDataClient.ek()};
MigratoryDataClient.dh=function(a,b,c){b=document.getElementById("MigratoryDataClient5");if(b===null){b=document.createElement("iframe");b.id="MigratoryDataClient5";b.style.display="none";document.body.appendChild(b)}var d=(new Date).getTime();b.src=a+"_"+c+d};
MigratoryDataClient.dr=function(a,b,c){this.em=new ActiveXObject("htmlfile");this.em.open();MigratoryDataClient.dq.indexOf(":")===-1?this.em.write("<html><head><script>document.domain='"+MigratoryDataClient.dq+"';<\/script></head><body></body></html>"):this.em.write("<html><head></head><body></body></html>");this.em.close();this.em.parentWindow.MigratoryDataClient0=this;b=this.em.createElement("iframe");b.id="eo";this.em.body.appendChild(b);this.em.fc=0;b.src=a+"_"+c};
MigratoryDataClient.dp=function(a){MigratoryDataClient.fd(a);MigratoryDataClient.em.fc+=a.length;MigratoryDataClient.em.fc>=MigratoryDataClient.fe&&MigratoryDataClient.aj===null&&MigratoryDataClient.ax!==MigratoryDataClient.bc&&MigratoryDataClient.et()};
MigratoryDataClient.ds=function(a,b,c){this.em={};this.em.en="XDR_HTML5";MigratoryDataClient.fc=0;b=document.getElementById("MigratoryDataClient1");if(b===null){b=document.createElement("iframe");b.id="MigratoryDataClient1";b.style.display="none";document.body.appendChild(b)}var d=(new Date).getTime();b.src=a+"_"+c+d};
MigratoryDataClient.ff=function(a){if(a.data.indexOf(MigratoryDataClient.a9.fg)!==-1){MigratoryDataClient.fd(a.data);MigratoryDataClient.fc+=a.data.length;MigratoryDataClient.fc>=MigratoryDataClient.fe&&MigratoryDataClient.aj===null&&MigratoryDataClient.ax!==MigratoryDataClient.bc&&MigratoryDataClient.et()}};
MigratoryDataClient.dm=function(a,b,c){window.frames["MigratoryDataClient2"+b].ew("window.parent.MigratoryDataClient.em = new XDomainRequest();");this.em.eu=0;this.em.en="XDR_STREAM";this.em.onload=function(){MigratoryDataClient.fh()};this.em.onprogress=function(){MigratoryDataClient.fh()};this.em.onerror=function(){};this.em.ontimeout=function(){};try{this.em.open("POST",a);this.em.send(c)}catch(d){}};
MigratoryDataClient.fh=function(){var a=this.em;if(a.responseText){for(var b=a.responseText.substring(a.eu),c=b.indexOf(this.a9.fi);c!==-1;){b=b.substring(0,c);this.fd(b);a.eu+=c+1;b=a.responseText.substring(a.eu);c=b.indexOf(this.a9.fi)}a.eu>=this.fe&&this.aj===null&&this.ax!==this.bc&&this.et()}};
MigratoryDataClient.dv=function(a,b,c){var d=this.o(a);if(d)this.em=this.f0(true);else window.frames["MigratoryDataClient2"+b].ew("window.parent.MigratoryDataClient.em = new XMLHttpRequest();");this.em.eu=0;this.em.onreadystatechange=function(){MigratoryDataClient.f9()};this.em.open("POST",a,true);d&&this.c.indexOf("WebKit")===0&&this.em.setRequestHeader("Content-Type","text/plain");this.em.send(c)};
MigratoryDataClient.f9=function(){var a=this.em;if(!(a===null||a.readyState!==3&&a.readyState!==4||a.status!==200)){if(this.c.indexOf("Opera")!==-1){this.em.ep!==undefined&&clearTimeout(this.em.ep);this.em.ep=setTimeout(function(){MigratoryDataClient.em.ep=undefined;MigratoryDataClient.f9()},this.fj)}if(a.responseText){for(var b=a.responseText.substring(a.eu),c=b.indexOf(this.a9.fi);c!==-1;){b=b.substring(0,c);this.fd(b);a.eu+=c+1;b=a.responseText.substring(a.eu);c=b.indexOf(this.a9.fi)}a.eu>=this.fe&&
this.aj===null&&this.ax!==this.bc&&this.et()}}};MigratoryDataClient.fk=function(){if(typeof XMLHttpRequest==="undefined"){try{return new ActiveXObject("Msxml2.XMLHTTP.6.0")}catch(a){}try{return new ActiveXObject("Msxml2.XMLHTTP.3.0")}catch(b){}try{return new ActiveXObject("Msxml2.XMLHTTP")}catch(c){}throw"Error: The browser does not support XMLHttpRequest!";}else return new XMLHttpRequest};
MigratoryDataClient.dd=function(a,b,c){var d=this.o(a);if(d)this.el=this.f0(false);else window.frames["MigratoryDataClient2"+b].ew("window.parent.MigratoryDataClient.el = ("+this.fk.toString()+")();");this.el.onreadystatechange=function(){MigratoryDataClient.f8()};this.el.open("POST",a,true);d&&this.c.indexOf("WebKit")===0&&this.el.setRequestHeader("Content-Type","text/plain");if(this.c.indexOf("IE")===0){this.el.setRequestHeader("Content-Type","text/plain");this.el.setRequestHeader("Connection",
"close")}this.el.send(c)};MigratoryDataClient.f8=function(){var a=this.el;a===null||typeof XMLHttpRequest!=="undefined"&&typeof a.aborted!=="undefined"&&a.aborted!==null&&a.aborted==true||a===null||a.readyState!==4||a.status!==200||a.responseText&&this.fd(a.responseText)};
MigratoryDataClient.de=function(a,b,c){var d;d=a.substring(0,a.indexOf("://"))==="http"?"ws://"+a.substring(a.indexOf("://")+3)+"WebSocketConnection":"wss://"+a.substring(a.indexOf("://")+3)+"WebSocketConnection-Secure";this.em=MigratoryDataClient.fl(d);this.d3=MigratoryDataClient.s();this.em.fm=this.d3;this.em.onmessage=function(e){MigratoryDataClient.fn(e.data)};this.em.onopen=function(){MigratoryDataClient.e3(a,b,c)};this.em.onclose=function(){if(MigratoryDataClient.d3===this.fm){MigratoryDataClient.cx();
MigratoryDataClient.b8++;MigratoryDataClient.bl(MigratoryDataClient.al);var e=MigratoryDataClient.t(MigratoryDataClient.b8);MigratoryDataClient.cv=setTimeout(function(){MigratoryDataClient.c0()},e)}}};MigratoryDataClient.fl=function(a){if(window.WebSocket)return new WebSocket(a);else if(window.MozWebSocket)return new MozWebSocket(a);return null};MigratoryDataClient.e3=function(a,b,c){this.em!=null&&this.em.readyState===1&&this.em.send(c)};
MigratoryDataClient.fn=function(a){var b=MigratoryDataClient.em;if(!(b===null||b.readyState!==1))if(a){b=a;for(var c=b.indexOf(MigratoryDataClient.a9.fi);c!==-1;){b=b.substring(0,c);MigratoryDataClient.fd(b);b=a.substring(c+1);c=b.indexOf(MigratoryDataClient.a9.fi)}}};MigratoryDataClient.fd=function(a){for(var b=0,c="\u0000",d={};;){var e=a.indexOf(this.a9.fg,b);if(e===-1)break;if(e-b>0){b=a.substring(b,e);c=b.charAt(0);d=this.fo(b);this.a8(c,d)}b=e+1}this.cj()};
MigratoryDataClient.fo=function(a){if(this.a9.fp[a.charAt(0)]!==undefined){for(var b=1,c={};;){if(b>=a.length)break;var d=a.charAt(b),e=a.indexOf(this.a9.fq,b+1);if(e===-1)return c;if(this.a9.fr[d]!==undefined){b++;var g="";switch(this.a9.fs[d]){case this.av.ft:g=this.fu(this.a9,a.substring(b,e));break;case this.av.fv:g=MigratoryDataClient.fw(this.a9,a.substring(b,e));break}b=c[d];if(b===undefined)c[d]=g;else if(c[d]instanceof Array)c[d][c[d].length]=g;else{c[d]=[];c[d][0]=b;c[d][1]=g}}b=e+1}return c}};
MigratoryDataClient.ey=function(a,b,c){var d="";d+=this.di.fx;d+=this.di.fy;d+=this.fz(this.di,a);d+=this.di.fq;d+=this.di.g0;d+=this.fz(this.di,b);d+=this.di.fq;d+=this.di.g1;d+=this.fz(this.di,c);d+=this.di.fq;d+=this.di.fg;return d};
MigratoryDataClient.dx=function(a,b,c,d,e,g,f,i,j){var h="";h+=g?d.g2:d.al;if(a!==null){h+=d.g3;h+=this.g4(d,a);h+=d.fq;if(this.c.indexOf("Opera")!==-1){h+=d.g5;h+=this.g4(d,1);h+=d.fq}}if(b!==null){h+=d.g1;h+=this.fz(d,b);h+=d.fq}if(c!==null){h+=d.fy;h+=this.fz(d,c);h+=d.fq}if(e!==null){h+=d.g6;h+=this.fz(d,e);h+=d.fq}if(f!==null){h+=d.g7;h+=this.fz(d,f);h+=d.fq}if(i!==null){h+=d.g8;h+=this.g4(d,i);h+=d.fq}h+=d.g9;h+=this.g4(d,j);h+=d.fq;h+=d.fg;return h};
MigratoryDataClient.e6=function(a,b,c,d,e){var g="";g+=e.an;g+=e.bm;g+=this.fz(e,a);g+=e.fq;if(c!==null){g+=e.g3;g+=this.g4(e,c);g+=e.fq;if(this.c.indexOf("Opera")!==-1){g+=e.g5;g+=this.g4(e,1);g+=e.fq}}if(d!==null){g+=e.az;g+=this.g4(e,d);g+=e.fq}a=this.ga(b);if(a==MigratoryDataClient.gb){g+=e.gc;g+=this.g4(e,b.history);g+=e.fq}else if(a==MigratoryDataClient.c4){g+=e.bx;g+=this.g4(e,b.seqid);g+=e.fq;g+=e.by;g+=this.g4(e,b.seq+1);g+=e.fq}g+=e.fg;return g};
MigratoryDataClient.ga=function(a){var b=MigratoryDataClient.c5;if(a.seqid!=Number.MAX_SAFE_INTEGER)if(a.nrOfConsecutiveRecovery>=MigratoryDataClient.gd){if(a.history>0)b=MigratoryDataClient.gb}else b=MigratoryDataClient.c4;else if(a.history>0)b=MigratoryDataClient.gb;if(b==MigratoryDataClient.c5||b==MigratoryDataClient.gb){a.cacheRecoveryStatus=MigratoryDataClient.cf;a.nrOfConsecutiveRecovery=0}return a.currentSubscribeType=b};
MigratoryDataClient.e8=function(a,b,c,d,e){b="";b+=e.ap;b+=e.bm;b+=this.fz(e,a);b+=e.fq;if(d!==null){b+=e.az;b+=this.g4(e,d);b+=e.fq}if(c!==null){b+=e.g3;b+=this.g4(e,c);b+=e.fq}b+=e.fg;return b};MigratoryDataClient.ea=function(a,b,c,d){var e="";e+=b.ai;e+=b.az;e+=this.g4(b,a);e+=b.fq;if(c!==null){e+=b.g3;e+=this.g4(b,c);e+=b.fq}if(d!==null){e+=b.b6;e+=this.g4(b,d);e+=b.fq}e+=b.fg;return e};
MigratoryDataClient.ed=function(a,b,c,d,e,g){var f="";f+=d.ar;f+=d.bm;f+=this.fz(d,a.subject);f+=d.fq;f+=d.bn;f+=this.fz(d,a.content);f+=d.fq;if(a.closure!==undefined&&a.closure!==null){f+=d.cc;f+=this.fz(d,a.closure);f+=d.fq}if(a.replySubject!==undefined&&a.replySubject!==null){f+=d.bp;f+=this.fz(d,a.replySubject);f+=d.fq}if(a.qos!==undefined&&a.qos!==null){if(a.qos==MigratoryDataClient.QOS_GUARANTEED){f+=d.c2;f+=this.g4(d,MigratoryDataClient.ge)}else{f+=d.c2;f+=this.g4(d,MigratoryDataClient.c3)}f+=
d.fq}if(a.retained!==undefined&&a.retained!==null){if(a.retained==true){f+=d.bq;f+=this.g4(d,1)}else{f+=d.bq;f+=this.g4(d,0)}f+=d.fq}if(b!==null){f+=d.g3;f+=this.g4(d,b);f+=d.fq;if(this.c.indexOf("Opera")!==-1){f+=d.g5;f+=this.g4(d,1);f+=d.fq}}if(c!==null){f+=d.az;f+=this.g4(d,c);f+=d.fq}if(g!==null){f+=d.b6;f+=this.g4(d,g);f+=d.fq}if(e!==null){f+=d.g6;f+=this.fz(d,e);f+=d.fq}f+=d.fg;return f};MigratoryDataClient.di={};MigratoryDataClient.di.fg="!";MigratoryDataClient.di.fi="z";
MigratoryDataClient.di.fq="$";MigratoryDataClient.di.gf="~";MigratoryDataClient.di.gg=" ";MigratoryDataClient.di.gh='"';MigratoryDataClient.di.gi="#";MigratoryDataClient.di.gj="%";MigratoryDataClient.di.gk="'";MigratoryDataClient.di.gl="/";MigratoryDataClient.di.gm="<";MigratoryDataClient.di.gn=">";MigratoryDataClient.di.go="[";MigratoryDataClient.di.gp="\\";MigratoryDataClient.di.gq="]";MigratoryDataClient.di.gr="^";MigratoryDataClient.di.gs="`";MigratoryDataClient.di.gt="{";
MigratoryDataClient.di.gu="|";MigratoryDataClient.di.gv="}";MigratoryDataClient.di.gw="";MigratoryDataClient.di.an="&";MigratoryDataClient.di.ap="(";MigratoryDataClient.di.aa=")";MigratoryDataClient.di.ai="*";MigratoryDataClient.di.fx="+";MigratoryDataClient.di.gx=",";MigratoryDataClient.di.ac="0";MigratoryDataClient.di.g2="2";MigratoryDataClient.di.ar="5";MigratoryDataClient.di.ae="8";MigratoryDataClient.di.ag=".";MigratoryDataClient.di.gy="B";MigratoryDataClient.di.al="D";
MigratoryDataClient.di.bm="&";MigratoryDataClient.di.bn="(";MigratoryDataClient.di.by=")";MigratoryDataClient.di.bx="*";MigratoryDataClient.di.g3="+";MigratoryDataClient.di.az=",";MigratoryDataClient.di.fy="-";MigratoryDataClient.di.g1=".";MigratoryDataClient.di.g0="?";MigratoryDataClient.di.as="0";MigratoryDataClient.di.gz="1";MigratoryDataClient.di.bv="2";MigratoryDataClient.di.g5="3";MigratoryDataClient.di.cc="4";MigratoryDataClient.di.b1="5";MigratoryDataClient.di.g6="7";
MigratoryDataClient.di.c6="8";MigratoryDataClient.di.b6="9";MigratoryDataClient.di.bq="A";MigratoryDataClient.di.c2="B";MigratoryDataClient.di.bo="J";MigratoryDataClient.di.g7="K";MigratoryDataClient.di.g8="L";MigratoryDataClient.di.b3="M";MigratoryDataClient.di.gc="N";MigratoryDataClient.di.bp="R";MigratoryDataClient.di.g9="S";MigratoryDataClient.di.ba="[";MigratoryDataClient.di.h0={};
(function(a){var b=a.h0;b["\u0000"]="y";for(var c=1;c<8;c++)b[String.fromCharCode(c)]=String.fromCharCode(c+39);b["\u0008"]="x";for(c=9;c<21;c++)b[String.fromCharCode(c)]=String.fromCharCode(c+39);b["\u0015"]="=";for(c=22;c<32;c++)b[String.fromCharCode(c)]=String.fromCharCode(c+41);b[a.fg]="I";b[a.fi]="w";b[a.fq]="J";b[a.gf]="K";b[a.gg]="L";b[a.gh]="M";b[a.gi]="N";b[a.gj]="O";b[a.gk]="P";b[a.gl]="_";b[a.gm]="Q";b[a.gn]="R";b[a.go]="S";b[a.gp]="T";b[a.gq]="U";b[a.gr]="V";b[a.gs]="W";b[a.gt]="X";b[a.gu]=
"Y";b[a.gv]="Z";b[a.gw]="v"})(MigratoryDataClient.di);MigratoryDataClient.di.h1={};(function(a){for(var b in a.h0)if(a.h0.hasOwnProperty(b))a.h1[a.h0[b]]=b})(MigratoryDataClient.di);MigratoryDataClient.a9={};MigratoryDataClient.a9.fg="";MigratoryDataClient.a9.fi="\u0019";MigratoryDataClient.a9.fq="\u001e";MigratoryDataClient.a9.gf="\u001f";MigratoryDataClient.a9.h2="\u0000";MigratoryDataClient.a9.h3="\n";MigratoryDataClient.a9.h4="\r";MigratoryDataClient.a9.gh='"';MigratoryDataClient.a9.gp="\\";
MigratoryDataClient.a9.an="\u0001";MigratoryDataClient.a9.ap="\u0002";MigratoryDataClient.a9.aa="\u0003";MigratoryDataClient.a9.ai="\u0004";MigratoryDataClient.a9.fx="\u0005";MigratoryDataClient.a9.gx="\u0006";MigratoryDataClient.a9.ac="\t";MigratoryDataClient.a9.g2="\u000c";MigratoryDataClient.a9.ar="\u0010";MigratoryDataClient.a9.ae="\u0013";MigratoryDataClient.a9.ag="\u0008";MigratoryDataClient.a9.gy="\u0017";MigratoryDataClient.a9.al="\u001a";MigratoryDataClient.a9.bm="\u0001";
MigratoryDataClient.a9.bn="\u0002";MigratoryDataClient.a9.by="\u0003";MigratoryDataClient.a9.bx="\u0004";MigratoryDataClient.a9.g3="\u0005";MigratoryDataClient.a9.az="\u0006";MigratoryDataClient.a9.fy="\u0007";MigratoryDataClient.a9.g1="\u0008";MigratoryDataClient.a9.g0="\t";MigratoryDataClient.a9.as="\u000b";MigratoryDataClient.a9.gz="\u000c";MigratoryDataClient.a9.bv="\u000e";MigratoryDataClient.a9.g5="\u000f";MigratoryDataClient.a9.cc="\u0010";MigratoryDataClient.a9.b1="\u0011";
MigratoryDataClient.a9.g6="\u0013";MigratoryDataClient.a9.c6="\u0014";MigratoryDataClient.a9.b6="\u0015";MigratoryDataClient.a9.bq="\u0017";MigratoryDataClient.a9.c2="\u0018";MigratoryDataClient.a9.g7="#";MigratoryDataClient.a9.g8="$";MigratoryDataClient.a9.b3="%";MigratoryDataClient.a9.bo="'";MigratoryDataClient.a9.gc="(";MigratoryDataClient.a9.bp=",";MigratoryDataClient.a9.g9="-";MigratoryDataClient.a9.ba="0";MigratoryDataClient.a9.h0={};
(function(a){var b=a.h0;b[a.fg]="\u0001";b[a.fq]="\u0002";b[a.gf]="\u0003";b[a.h2]="\u0004";b[a.h3]="\u0005";b[a.h4]="\u0006";b[a.gh]="\u0007";b[a.gp]="\u0008";b[MigratoryDataClient.di.fg]="\t";b[a.fi]="\u000b"})(MigratoryDataClient.a9);MigratoryDataClient.a9.h1={};(function(a){for(var b in a.h0)if(a.h0.hasOwnProperty(b))a.h1[a.h0[b]]=b})(MigratoryDataClient.a9);MigratoryDataClient.a9.fp={};
(function(a){a.fp[a.an]=true;a.fp[a.ap]=true;a.fp[a.aa]=true;a.fp[a.ai]=true;a.fp[a.fx]=true;a.fp[a.gx]=true;a.fp[a.ac]=true;a.fp[a.g2]=true;a.fp[a.ar]=true;a.fp[a.ae]=true;a.fp[a.ag]=true;a.fp[a.gy]=true;a.fp[a.al]=true})(MigratoryDataClient.a9);MigratoryDataClient.a9.fr={};
(function(a){a.fr[a.bm]=true;a.fr[a.bn]=true;a.fr[a.by]=true;a.fr[a.bx]=true;a.fr[a.g3]=true;a.fr[a.az]=true;a.fr[a.fy]=true;a.fr[a.g1]=true;a.fr[a.g0]=true;a.fr[a.as]=true;a.fr[a.gz]=true;a.fr[a.bv]=true;a.fr[a.g5]=true;a.fr[a.b1]=true;a.fr[a.g6]=true;a.fr[a.c6]=true;a.fr[a.b6]=true;a.fr[a.bo]=true;a.fr[a.g7]=true;a.fr[a.g8]=true;a.fr[a.cc]=true;a.fr[a.gc]=true;a.fr[a.b3]=true;a.fr[a.bp]=true;a.fr[a.g9]=true;a.fr[a.ba]=true;a.fr[a.bq]=true;a.fr[a.c2]=true})(MigratoryDataClient.a9);
MigratoryDataClient.av={};MigratoryDataClient.av.h5=1;MigratoryDataClient.av.h6=2;MigratoryDataClient.av.fv=3;MigratoryDataClient.av.ft=4;MigratoryDataClient.av.h7={};(function(a){var b=a.h7;b.bm=a.fv;b.bn=a.fv;b.by=a.ft;b.bx=a.ft;b.g3=a.ft;b.az=a.ft;b.fy=a.fv;b.g1=a.fv;b.g0=a.fv;b.as=a.ft;b.gz=a.fv;b.bv=a.ft;b.g5=a.ft;b.g6=a.fv;b.c6=a.fv;b.b6=a.ft;b.bo=a.fv;b.g7=a.fv;b.g8=a.ft;b.cc=a.fv;b.b1=a.ft;b.b3=a.ft;b.bp=a.fv;b.g9=a.ft;b.ba=a.fv;b.bq=a.ft;b.c2=a.ft})(MigratoryDataClient.av);
MigratoryDataClient.a9.fs={};MigratoryDataClient.di.fs={};(function(){for(var a in MigratoryDataClient.av.h7)if(MigratoryDataClient.av.h7.hasOwnProperty(a)){MigratoryDataClient.a9.fs[MigratoryDataClient.a9[a]]=MigratoryDataClient.av.h7[a];MigratoryDataClient.di.fs[MigratoryDataClient.di[a]]=MigratoryDataClient.av.h7[a]}})();MigratoryDataClient.av.aw={};MigratoryDataClient.av.aw[0]="UNKNOWN_SESSION_ID";
MigratoryDataClient.fz=function(a,b){for(var c="",d=0;d<b.length;d++){var e=a.h0[b.charAt(d)];if(e!==undefined){c+=a.gf;c+=e}else c+=b.charAt(d)}return c};MigratoryDataClient.fw=function(a,b){for(var c="",d=0;d<b.length;d++){var e=b.charAt(d);if(e===a.gf){if(d+1>=b.length||a.h1[b.charAt(d+1)]===undefined)throw"Error: fw() Illegal argument '"+b+"'!";e=a.h1[b.charAt(d+1)];d++}c+=e}return c};
MigratoryDataClient.g4=function(a,b){if((b&4294967168)===0){var c=String.fromCharCode(b),d=a.h0[c];return d===undefined?c:a.gf+d}var e;e=(b&4278190080)!==0?24:(b&16711680)!==0?16:8;c=[];for(d=0;d<10;d++)c.push(0);for(var g=0,f=0;e>=0;){var i=b>>e&255;f++;c[g]|=i>>f;d=a.h0[String.fromCharCode(c[g])];if(d!==undefined){c[g]=a.gf.charCodeAt(0);c[g+1]=d.charCodeAt(0);g++}g++;c[g]|=i<<7-f&127;e-=8}d=a.h0[String.fromCharCode(c[g])];if(d!==undefined){c[g]=a.gf.charCodeAt(0);c[g+1]=d.charCodeAt(0);g++}g++;
a="";for(d=0;d<g;d++)a+=String.fromCharCode(c[d]);return a};
MigratoryDataClient.fu=function(a,b){var c="Error: fu() Illegal argument '"+b+"'!",d=0,e=-1,g=0,f,i=b.length,j=0;if(i===1)return b.charCodeAt(0);else if(i===2&&b.charAt(0)===a.gf){f=a.h1[b.charAt(1)];if(f!==undefined)return f.charCodeAt(0);else throw c;}for(;i>0;i--){f=b.charAt(j);j++;if(f===a.gf){if(i-1<0)throw c;i--;f=b.charAt(j);j++;f=a.h1[f];if(f===undefined)throw c;}else f=f;if(e>0){g|=f.charCodeAt(0)>>e;d=d<<8|g;g=f.charCodeAt(0)<<8-e}else g=f.charCodeAt(0)<<-e;e=(e+7)%8}return d};
MigratoryDataClient.NOTIFY_UNSUPPORTED_BROWSER="NOTIFY_UNSUPPORTED_BROWSER";MigratoryDataClient.NOTIFY_SERVER_DOWN="NOTIFY_SERVER_DOWN";MigratoryDataClient.NOTIFY_SERVER_UP="NOTIFY_SERVER_UP";MigratoryDataClient.NOTIFY_DATA_RESYNC="NOTIFY_DATA_RESYNC";MigratoryDataClient.NOTIFY_DATA_SYNC="NOTIFY_DATA_SYNC";MigratoryDataClient.NOTIFY_PUBLISH_OK="NOTIFY_PUBLISH_OK";MigratoryDataClient.NOTIFY_PUBLISH_FAILED="NOTIFY_PUBLISH_FAILED";MigratoryDataClient.NOTIFY_PUBLISH_DENIED="NOTIFY_PUBLISH_DENIED";
MigratoryDataClient.NOTIFY_PUBLISH_NO_SUBSCRIBER="NOTIFY_PUBLISH_NO_SUBSCRIBER";MigratoryDataClient.NOTIFY_SUBSCRIBE_ALLOW="NOTIFY_SUBSCRIBE_ALLOW";MigratoryDataClient.NOTIFY_SUBSCRIBE_DENY="NOTIFY_SUBSCRIBE_DENY";MigratoryDataClient.NOTIFY_SUBSCRIBE_TIMEOUT="NOTIFY_SUBSCRIBE_TIMEOUT";MigratoryDataClient.NOTIFY_RECONNECT_RATE_EXCEEDED="NOTIFY_RECONNECT_RATE_EXCEEDED";MigratoryDataClient.CONSTANT_WINDOW_BACKOFF="CONSTANT_WINDOW_BACKOFF";MigratoryDataClient.TRUNCATED_EXPONENTIAL_BACKOFF="TRUNCATED_EXPONENTIAL_BACKOFF";
MigratoryDataClient.QOS_STANDARD="QOS_STANDARD";MigratoryDataClient.QOS_GUARANTEED="QOS_GUARANTEED";MigratoryDataClient.MESSAGE_TYPE_SNAPSHOT="MESSAGE_TYPE_SNAPSHOT";MigratoryDataClient.MESSAGE_TYPE_UPDATE="MESSAGE_TYPE_UPDATE";MigratoryDataClient.MESSAGE_TYPE_RECOVERED="MESSAGE_TYPE_RECOVERED";MigratoryDataClient.MESSAGE_TYPE_HISTORICAL="MESSAGE_TYPE_HISTORICAL";
MigratoryDataClient.connect=function(){if(this.h8)throw"Error: connect() - already connected";if(this.bi===undefined||this.bi===null||this.bi.length==0)throw"Error: connect() - no server to connect to; use setServers() to specify one or more servers";if(this.ca===undefined||this.ca===null)throw"Error: connect() - no message handler; use setMessageHandler() to specify a message handler";if(this.d===undefined||this.d===null)throw"Error: connect() - no status handler; use setStatusHandler() to specify a status handler";
this.h8=true;var a={};a.ak=this.al;this.cp(a);if(this.er.length>0){a={};a.ak=this.an;a.c8=this.a2(this.er);a.e5=this.a0(this.h9,[]);a.e4=true;this.cp(a)}};MigratoryDataClient.notifyAfterReconnectRetries=function(a){if(this.h8)throw"Error: notifyAfterReconnectRetries() - already connected; use this method before connect()";if(typeof a!=="number"||a<1)throw"Error: notifyAfterReconnectRetries() - invalid argument; expected a positive integer";this.d1=a};
MigratoryDataClient.setServers=function(a){if(this.h8)throw"Error: setServers() - already connected; use this method before connect()";this.a6("setServers",a,"string",1,/^(\d+)?\s*https?:\/\/(\w|-)+(\.(\w|-)+)*(:\d+)?$/i,"Error: setServers() - invalid argument; expected a list of URLs");for(var b=[],c=0;c<a.length;c++){var d=/https?:\/\/(\w|-)+(\.(\w|-)+)*(:\d+)?$/i.exec(a[c])[0],e=/^\d+/.exec(a[c]);if(e===null)e=100;else{e=parseInt(e[0]);if(e>100)throw"Error: setServers() - invalid weight; expected a number between 0 and 100";
}this.d8||this.d9(d);b.push({m:d,cu:e})}this.bi=b;this.bd.be=[];for(c=0;c<a.length;c++){this.bd.be[c]={};this.bd.be[c].bg=0;this.bd.be[c].cq=0;this.bd.be[c].bk=0;this.bd.be[c].cl=0;this.bd.be[c].c1=0;this.bd.be[c].aw={}}};MigratoryDataClient.getSubjects=function(){return this.a2(this.er)};
MigratoryDataClient.setMessageHandler=function(a){if(this.h8)throw"Error: setMessageHandler() - already connected; use this method before connect()";if(typeof a!=="function")throw"Error: setMessageHandler() - invalid argument; expected a function";this.ca=a};
MigratoryDataClient.setStatusHandler=function(a){if(this.h8)throw"Error: setStatusHandler() - already connected; use this method before connect()";if(typeof a!=="function")throw"Error: setStatusHandler() - invalid argument; expected a function";this.d=a};MigratoryDataClient.subscribe=function(a){MigratoryDataClient.subscribeWithHistory(a,0)};
MigratoryDataClient.subscribeWithHistory=function(a,b){this.a7("subscribeWithHistory",a,"string",1,"Error: subscribe() - invalid first argument; expected a list of valid topics");if(typeof b!=="number"||b<0)throw"Error: subscribeWithHistory() - invalid second argument; expected an integer higher or equal to 0";a=this.a3(a,this.er);if(a.length!==0){for(var c=0;c<a.length;c++)this.h9[a[c]]=b;this.er=this.a5(this.er,a);if(this.h8){b={};b.ak=this.an;b.c8=a;b.e5=this.a0(this.h9,a);b.e4=true;this.cp(b)}}};
MigratoryDataClient.unsubscribe=function(a){this.a7("unsubscribe",a,"string",1,"Error: unsubscribe() - invalid argument; expected a list of valid topics");a=this.a4(a,this.er);if(a.length!==0){for(var b=0;b<a.length;b++)delete this.h9[a[b]];this.er=this.a3(this.er,a);if(this.h8){b={};b.ak=this.ap;b.c8=a;this.cp(b)}}};MigratoryDataClient.disconnect=function(){if(this.h8){this.h8=false;this.b(false)&&this.eq()}};
MigratoryDataClient.setEntitlementToken=function(a){if(this.h8)throw"Error: setEntitlementToken() - already connected; use this method before connect()";this.dy=a};
MigratoryDataClient.setNumberOfSubdomainLevels=function(a){if(this.h8)throw"Error: setNumberOfSubdomainLevels() - already connected; use this method before connect()";if(this.bi.length>0)throw"Error: setNumberOfSubdomainLevels() - unable to set the number of subdomain levels when servers are already configured; use this method before setServers()";if(typeof a!=="number"||a<2)throw"Error: setNumberOfSubdomainLevels() - invalid argument; expected an integer higher or equal to 2";this.n=a};
MigratoryDataClient.getInfo=function(){if(!this.h8)throw"Error: getInfo() - not connected; use this method after connect()";s="Date: "+(new Date).toString()+"\n";s+="Uptime: "+((new Date).getTime()-this.bd.ha)+" ms\n";s+="window.location: "+window.location+"\n";s+="document.domain: "+document.domain+"\n";s+="User-agent: "+navigator.userAgent+"\n";s+="Detected browser: "+this.c+"\n";s+="Servers: ";for(var a=0;a<this.bi.length;a++){if(a>0)s+=", ";s+=this.bi[a].cu+" "+this.bi[a].m}s+="\nSubjects: "+
this.c8.toString()+"\n";s+="Connection status ["+(this.bf===null?null:this.bi[this.bf].m)+"]: "+this.ax+"\n";s+="Time from last server activity: "+(this.bd.ck!==null?(new Date).getTime()-this.bd.ck:null)+" ms\n";s+="Servers down before notify: "+this.d1+"\n";s+="Consecutive server down count: "+this.b7+" times\n";for(a=0;a<this.bd.be.length;a++){s+="\nServer up ["+this.bi[a].m+"]: "+this.bd.be[a].bg+" times\n";s+="Server down ["+this.bi[a].m+"]: "+this.bd.be[a].cq+" times\n";s+="Server connection recycled ["+
this.bi[a].m+"]: "+this.bd.be[a].bk+" times\n";s+="Received server events ["+this.bi[a].m+"]: "+this.bd.be[a].cl+"\n";s+="Received messages ["+this.bi[a].m+"]: "+this.bd.be[a].c1+"\n";for(var b in this.bd.be[a].aw)if(this.bd.be[a].aw.hasOwnProperty(b))s+="Error ["+this.bi[a].m+"] x"+this.bd.be[a].aw[b]+" times : "+b+"\n"}return s};
MigratoryDataClient.publish=function(a){if(!this.h8)throw"Error: publish() - not connected; use this method after connect()";if(a===undefined||a===null)throw"Error: publish() - invalid argument; expected a valid message";if(a.subject===undefined||a.subject===null)throw"Error: publish() - invalid argument; expected a valid message with a non-empty topic";this.a7("publish",[a.subject],"string",1,"Error: publish() - invalid argument; expected a valid message,  "+a.subject+" is the cause of the error");
if(a.content===undefined||a.content===null)throw"Error: publish() - invalid argument; expected a valid message with a non-empty content";a.replySubject!==undefined&&a.replySubject!==null&&MigratoryDataClient.subscribe([a.replySubject]);var b={};b.ak=this.ar;b.ec=a;this.cp(b)};
MigratoryDataClient.setQuickReconnectMaxRetries=function(a){if(this.h8)throw"Error: setQuickReconnectMaxRetries() - already connected; use this method before connect()";if(typeof a!=="number"||a<2)throw"Error: setQuickReconnectMaxRetries() - invalid argument; expected an integer higher or equal to 2";this.v=a};
MigratoryDataClient.setQuickReconnectInitialDelay=function(a){if(this.h8)throw"Error: setQuickReconnectInitialDelay() - already connected; use this method before connect()";if(typeof a!=="number"||a<1)throw"Error: setQuickReconnectInitialDelay() - invalid argument; expected an integer higher or equal to 1";this.w=a*1E3};
MigratoryDataClient.setReconnectPolicy=function(a){if(this.h8)throw"Error: setReconnectPolicy()  - already connected; use this method before connect()";if(a===undefined||a!==MigratoryDataClient.CONSTANT_WINDOW_BACKOFF&&a!==MigratoryDataClient.TRUNCATED_EXPONENTIAL_BACKOFF)throw"Error: setReconnectPolicy() - invalid argument; expected CONSTANT_WINDOW_BACKOFF or TRUNCATED_EXPONENTIAL_BACKOFF";this.x=a};
MigratoryDataClient.setReconnectTimeInterval=function(a){if(this.h8)throw"Error: setReconnectTimeInterval() - already connected; use this method before connect()";if(typeof a!=="number"||a<1)throw"Error: setReconnectTimeInterval() - invalid argument; expected an integer higher or equal to 1";this.y=a*1E3};
MigratoryDataClient.setReconnectMaxDelay=function(a){if(this.h8)throw"Error: setReconnectMaxDelay() - already connected; use this method before connect()";if(typeof a!=="number"||a<1)throw"Error: setReconnectMaxDelay() - invalid argument; expected an integer higher or equal to 1";this.z=a*1E3};
MigratoryDataClient.notifyWhenReconnectRateExceedsThreshold=function(a){if(this.h8)throw"Error: notifyWhenReconnectRateExceedsThreshold() - already connected; use this method before connect()";if(typeof a!=="number"||a<2)throw"Error: notifyWhenReconnectRateExceedsThreshold() - invalid argument; expected an integer higher or equal to 2";this.ct=a};
MigratoryDataClient.pause=function(){if(!this.h8)throw"Error: pause() - not connected; use this method after connect()";if(MigratoryDataClient.hb!=false){MigratoryDataClient.hb=false;var a={};a.ak=this.ei;this.cp(a)}};MigratoryDataClient.resume=function(){if(!this.h8)throw"Error: resume() - not connected; use this method after connect()";if(MigratoryDataClient.hb!=true){MigratoryDataClient.hb=true;var a={};a.ak=this.ej;this.cp(a)}};MigratoryDataClient.dz=6;MigratoryDataClient.d8=false;
MigratoryDataClient.db=false;MigratoryDataClient.dg=false;MigratoryDataClient.co=9E5;MigratoryDataClient.hc=3E4+Math.floor(Math.random()*1E4);MigratoryDataClient.b4=MigratoryDataClient.hc;MigratoryDataClient.u=1E4;MigratoryDataClient.fj=100;MigratoryDataClient.fe=524288;MigratoryDataClient.d1=1;MigratoryDataClient.ct=10;MigratoryDataClient.n=0;MigratoryDataClient.b2=false;MigratoryDataClient.gd=2;MigratoryDataClient.v=3;MigratoryDataClient.w=5E3;MigratoryDataClient.x=MigratoryDataClient.TRUNCATED_EXPONENTIAL_BACKOFF;
MigratoryDataClient.y=2E4;MigratoryDataClient.z=36E4;MigratoryDataClient.dy=null;MigratoryDataClient.ci=null;MigratoryDataClient.hb=true;MigratoryDataClient.an="SUBSCRIBE";MigratoryDataClient.ap="UNSUBSCRIBE";MigratoryDataClient.ai="PING";MigratoryDataClient.al="CONNECT";MigratoryDataClient.ar="PUBLISH";MigratoryDataClient.ei="PAUSE";MigratoryDataClient.ej="RESUME";MigratoryDataClient.hd=0;MigratoryDataClient.dn=1;MigratoryDataClient.dt=2;MigratoryDataClient.dc=3;MigratoryDataClient.he=4;
MigratoryDataClient.du=5;MigratoryDataClient.hf=6;MigratoryDataClient.hg=7;MigratoryDataClient.df=8;MigratoryDataClient.dl=9;MigratoryDataClient.dj=10;MigratoryDataClient.ay="SERVER_UP";MigratoryDataClient.cz="SERVER_DOWN";MigratoryDataClient.bc="SERVER_RECYCLE";MigratoryDataClient.c3=0;MigratoryDataClient.ge=1;MigratoryDataClient.bs="1";MigratoryDataClient.hh="2";MigratoryDataClient.bt="3";MigratoryDataClient.bu="4";MigratoryDataClient.dw=1;MigratoryDataClient.e1="ERROR_TIMEOUT";
MigratoryDataClient.hi="ERROR_HTTP";MigratoryDataClient.au="ERROR_SERVER";MigratoryDataClient.c5="SUBSCRIBE_TYPE_NORMAL";MigratoryDataClient.gb="SUBSCRIBE_TYPE_HISTORY";MigratoryDataClient.c4="SUBSCRIBE_TYPE_RECOVERY";MigratoryDataClient.cf="cache_ok";MigratoryDataClient.ch="cache_ok_no_new_message";MigratoryDataClient.cg="cache_ok_new_epoch";MigratoryDataClient.hj="no_cache";MigratoryDataClient.hk="no_seq";MigratoryDataClient.ce="end";MigratoryDataClient.hl=0;MigratoryDataClient.hm=1;
MigratoryDataClient.c7=2;MigratoryDataClient.c=MigratoryDataClient.a();MigratoryDataClient.dq=null;MigratoryDataClient.bi=[];MigratoryDataClient.ca=null;MigratoryDataClient.d=null;MigratoryDataClient.c9=[];MigratoryDataClient.cs=0;MigratoryDataClient.cr=(new Date).getTime();MigratoryDataClient.eh=false;MigratoryDataClient.j=[];MigratoryDataClient.h=false;MigratoryDataClient.bf=null;MigratoryDataClient.ax=null;MigratoryDataClient.er=[];MigratoryDataClient.h9={};MigratoryDataClient.c8=[];
MigratoryDataClient.br={};MigratoryDataClient.b0=null;MigratoryDataClient.b5=null;MigratoryDataClient.em=null;MigratoryDataClient.cn=(new Date).getTime();MigratoryDataClient.cm=null;MigratoryDataClient.d0=[];MigratoryDataClient.b7=0;MigratoryDataClient.b8=0;MigratoryDataClient.bh=false;MigratoryDataClient.d3=null;MigratoryDataClient.ee=[];MigratoryDataClient.aj=null;MigratoryDataClient.el=null;MigratoryDataClient.e0=null;MigratoryDataClient.cv=null;MigratoryDataClient.bd={};
MigratoryDataClient.bd.ha=(new Date).getTime();MigratoryDataClient.bd.ck=null;MigratoryDataClient.bd.be=[];MigratoryDataClient.d7=false;MigratoryDataClient.dk=false;MigratoryDataClient.h8=false;if(!Number.MAX_SAFE_INTEGER)Number.MAX_SAFE_INTEGER=Math.pow(2,53)-1;if(window.WebSocket)MigratoryDataClient.d7=true;else if(window.MozWebSocket)MigratoryDataClient.d7=true;
if(typeof MigratoryDataClient_Disable_WebSocket_Transport!=="undefined"&&MigratoryDataClient_Disable_WebSocket_Transport==true)MigratoryDataClient.d7=false;if(MigratoryDataClient.d7==false)if(window.XDomainRequest){var xdrTest=new XDomainRequest;try{xdrTest.open("GET",window.location.protocol+"//127.0.0.1");xdrTest.send();MigratoryDataClient.dk=true;xdrTest.abort()}catch(e$$7){xdrTest.abort();MigratoryDataClient.dk=false}}else MigratoryDataClient.dk=false;
if(MigratoryDataClient.c==="IE")try{window.attachEvent("onunload",function(){MigratoryDataClient.eq()})}catch(e$$8){window.addEventListener("unload",function(){MigratoryDataClient.eq()},false)}else window.addEventListener("unload",function(){MigratoryDataClient.eq()},false);MigratoryDataClient.e();if(MigratoryDataClient.c==="WebKit iPhone")MigratoryDataClient.fe=65536;else if(MigratoryDataClient.c==="Opera Mobile"){MigratoryDataClient.fe=32768;MigratoryDataClient.fj=500}
if(MigratoryDataClient.d7==true){MigratoryDataClient.d8=true;MigratoryDataClient.db=true;MigratoryDataClient.dg=true}else if(MigratoryDataClient.dk&&window.postMessage){MigratoryDataClient.d8=true;MigratoryDataClient.db=true;MigratoryDataClient.dg=true;try{window.attachEvent("onmessage",MigratoryDataClient.ff)}catch(e$$9){window.addEventListener("onmessage",MigratoryDataClient.ff,false)}}else if(XMLHttpRequest&&(new XMLHttpRequest).withCredentials!==undefined){MigratoryDataClient.d8=true;MigratoryDataClient.db=
true}else if(swfobject&&swfobject.hasFlashPlayerVersion("9")&&(typeof MigratoryDataClient_Allow_Flash_Transport==="undefined"||MigratoryDataClient_Allow_Flash_Transport==true)){MigratoryDataClient.d8=true;MigratoryDataClient.i(function(){MigratoryDataClient.fa()})}if(!MigratoryDataClient.d8||MigratoryDataClient.db)MigratoryDataClient.i(function(){MigratoryDataClient.ek()});
